In [5]:
import pandas as pd
import os
import glob

In [4]:
# Concatenate monthly tenders files
as_tenders_root = r"/Users/saurabhlevin/Deployment/flood-data-ecosystem-Assam/Sources/TENDERS/data/monthly_tenders"
if not os.path.isdir(as_tenders_root):
    raise FileNotFoundError(f"Directory not found: {as_tenders_root}")

csv_files = glob.glob(os.path.join(as_tenders_root, "*.csv"))
frames = []
for file in csv_files:
    try:
        df = pd.read_csv(file)
        frames.append(df)
    except Exception as e:
        print(f"Failed to read {file}: {e}")

if frames:
    as_tenders = pd.concat(frames, ignore_index=True)
else:
    as_tenders = pd.DataFrame()

as_tenders.shape

(29992, 29)

In [12]:
hp_all_tenders = pd.read_csv(r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-Himachal-Pradesh/Sources/TENDERS/data/all_tenders.csv')
hp_all_tenders = hp_all_tenders.loc[hp_all_tenders['Status'] == 'Accepted-AOC']
hp_all_tenders = hp_all_tenders.loc[hp_all_tenders['Awarded Value'].notnull()]
print(f"Number of accepted tenders: {len(hp_all_tenders)}")
hp_all_tenders

Number of accepted tenders: 9035

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,Organisation Chain,location,Pincode,No of Bids Received,Tender Value in ₹,Bidder Name,Awarded Value,Status,Contract Date :,Department
0,2019_PWD_26625_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Hawan to B...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,PWD,Bilaspur,174001.0,2.0,"18,74,878",Pradeep Kumar,"2,235,643",Accepted-AOC,24-Jan-2021,PWD
1,2019_PWD_26627_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Harlog haw...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,PWD,Bilaspur,174001.0,2.0,"16,37,744",Pradeep Kumar,"2,025,021",Accepted-AOC,24-Jan-2021,PWD
2,2019_PWD_26628_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Lethwin la...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Coal,No,No,...,PWD,Bilaspur,174001.0,2.0,"15,98,780",Pradeep Kumar,"1,970,194",Accepted-AOC,24-Jan-2021,PWD
3,2019_PWD_26663_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Massour mo...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,PWD,Bilaspur,174001.0,2.0,"8,92,860",Pradeep Kumar,"1,147,224",Accepted-AOC,24-Jan-2021,PWD
4,2019_PWD_26666_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Construction of Jarlu Tyamat Gujjar Basti Uppe...,"ROFD, CD,GSB,WMB,Road side drain, metalling an...",Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,PWD,Bilaspur,174001.0,2.0,"90,22,033",HAKAM CHAND,"11,135,455",Accepted-AOC,24-Jan-2021,PWD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52027,2020_PWD_34028_1,SD-I-CTR-2019-20-21223 dt 4-1-2020,Elysium Devidhar road km. 0/00 to 12/330 (SH P...,Elysium Devidhar road km. 0/00 to 12/330 (SH P...,Works,Open Tender,Item Rate,Civil Works,No,No,...,PWD,Shimla,171003.0,2.0,"14,63,794",GAYATRI TEGTA,"1,448,961",Accepted-AOC,08-Mar-2020,PWD
52030,2020_PWD_34337_1,ED.II.GA.Tender/19-20-8501-02 dated 21.01.2020,Construction of new OPD blocb at IGMC Shimla S...,Providing high mast light,Works,Open Tender,Item Rate,Electrical Works,No,No,...,PWD,shimla,171001.0,1.0,"16,60,695",D.S Ranta Electrical Contractor,"1,658,797",Accepted-AOC,05-Mar-2020,PWD
52038,2020_PWD_35194_1,C/O Link road to Harizan Basti Lahra,C/O Link road to Harizan Basti Lahra,Providing and laying soling and M/T in km 0/10...,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,PWD,Barsar,174305.0,2.0,"14,78,410",dinesh kumar,"2,259,664",Accepted-AOC,13-Mar-2020,PWD
52040,2020_UDDHP_34616_1,MCU/E-TENDER/2020/110-116,Repair and Restoration of drain from h/o Raj R...,Repair and Restoration of drain from h/o Raj R...,Works,Open Tender,Item Rate,Civil Works - Others,No,No,...,Directorate of Urban Development||Urban Develo...,Prem Nagar Ward No. 1 MC Una,174303.0,2.0,"3,97,980",MAHESH ANGRA,"380,519",Accepted-AOC,17-Mar-2020,Directorate of Urban Development||Urban Develo...
52044,2020_YSPU_35067_1,UHF/Const-1/Partfile/2019/2751 Dtd 14-02-2020,Providing floor and wall tiles in farmers host...,Providing floor and wall tiles in farmers host...,Works,Open Tender,Item Rate,Civil Works,No,No,...,Dr. Yashwant Singh Parmar University of Hortic...,KVK Kandaghat,173215.0,2.0,"3,10,556",Dinesh Thakur,"276,247",Accepted-AOC,04-Mar-2020,Dr. Yashwant Singh Parmar University of Hortic...

In [13]:
hp_all_tenders['Awarded Value'].str.replace(',','').astype(float).sum()

np.float64(63660798168.967)

In [11]:
hp_flood_tenders = pd.read_csv(r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-Himachal-Pradesh/Sources/TENDERS/data/flood_tenders_all.csv')
hp_flood_tenders = hp_flood_tenders.loc[hp_flood_tenders['Status'] == 'Accepted-AOC']
hp_flood_tenders = hp_flood_tenders.loc[hp_flood_tenders['Awarded Value'].notnull()]
print(f"Number of accepted tenders: {len(hp_flood_tenders)}")
hp_flood_tenders

Number of accepted tenders: 3959

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,is_flood_tender,positive_keywords_dict,negative_keywords_dict,Season,Scheme,Erosion,Roads_Bridges_Embkt,Response Type,Flood Response - Subhead,month
0,2019_PWD_26625_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Hawan to B...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Preparedness Measures,{'maintenance': 1},2021_01
1,2019_PWD_26627_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Harlog haw...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Preparedness Measures,{'maintenance': 1},2021_01
2,2019_PWD_26628_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Providing periodical maintenance of Lethwin la...,Providing and laying 25mm thick bitumen concrete.,Works,Open Tender,Item Rate,Coal,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Preparedness Measures,{'maintenance': 1},2021_01
3,2019_PWD_26666_1,PW-BLP1-CB-eproc/18-19303-60 dt 15.1.19,Construction of Jarlu Tyamat Gujjar Basti Uppe...,"ROFD, CD,GSB,WMB,Road side drain, metalling an...",Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Repair and Restoration,"{'construction': 1, 'drain': 1}",2021_01
4,2019_PWD_28647_1,PW-BLP1-CB-eproc/19-22506-50 dt 27.2.19,Special repair to 144.00 mtr span prestressed ...,Lethwin side approaches.,Works,Open Tender,Item Rate,Civil Works - Bridges,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Repair and Restoration,"{'repair': 1, 'bridge': 1}",2021_01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,2019_PWD_32779_1,PW-MDI-Tender-NIT- 15834-63 dated 13.11.2019,Construction of Pakhari Galu Baragaon road and...,"F/C 5/7 mtr. wide including passing places, c/...",Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Post-Monsoon,NaN,False,True,Repair and Restoration,"{'construction': 1, 'bridge': 2, 'drain': 1}",2020_03
13576,2019_PWD_32788_1,PW-MDI-Tender-NIT- 15834-63 dated 13.11.2019,Metalling and tarring on Nagrota Segaldugh Cha...,"ROFD, C/O and breast wall, cross drainage work...",Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Post-Monsoon,NaN,False,True,Repair and Restoration,{'drain': 1},2020_03
13577,2019_SIDC_31737_1,Job No. 2,"Construction of road and road side drain, R/wa...","Construction of road and road side drain, R/wa...",Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Monsoon,NaN,False,True,Repair and Restoration,"{'construction': 2, 'drain': 2}",2020_03
13578,2020_PWD_34028_1,SD-I-CTR-2019-20-21223 dt 4-1-2020,Elysium Devidhar road km. 0/00 to 12/330 (SH P...,Elysium Devidhar road km. 0/00 to 12/330 (SH P...,Works,Open Tender,Item Rate,Civil Works,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Others,NaN,2020_03
13579,2020_PWD_35194_1,C/O Link road to Harizan Basti Lahra,C/O Link road to Harizan Basti Lahra,Providing and laying soling and M/T in km 0/10...,Works,Open Tender,Item Rate,Civil Works - Roads,No,No,...,True,"{'flood': 0, 'landslide': 0, 'flash flood': 0,...","{'Flood Lights': 0, 'pipe': 0, 'pipes': 0, 'su...",Pre-Monsoon,NaN,False,True,Others,NaN,2020_03

In [14]:
hp_flood_tenders['Awarded Value'].str.replace(',','').astype(float).sum()

np.float64(31575320233.019997)

In [ ]:
import pandas as pd

def tender_count_by_fy(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    df["Published Date"] = pd.to_datetime(
        df["Published Date"], format="%d-%b-%Y %I:%M %p", errors="coerce"
    )
    def to_fy(dt):
        if pd.isna(dt): return None
        year = dt.year if dt.month >= 4 else dt.year - 1
        return f"{year}-{str(year + 1)[2:]}"
    df["FY"] = df["Published Date"].apply(to_fy)
    return df.groupby("FY").size().reset_index(name="Count")

result = tender_count_by_fy("data/flood_tenders_all.csv")
print(result.to_string(index=False))
print(f"\nTotal: {result['Count'].sum()}")

generate a function that will give the annual value of tenders in the financial year 2025-2026 from /Users/saurabhlevin/Deployment/flood-data-ecosystem-Assam/Sources/TENDERS/data/assam_all_tenders.csv

In [ ]:
import pandas as pd

def annual_tender_value_fy2025_26(csv_path: str) -> tuple[float, int]:
    df = pd.read_csv(csv_path)
    df["Published Date"] = pd.to_datetime(
        df["Published Date"], format="%d-%b-%Y %I:%M %p", errors="coerce"
    )
    mask = (df["Published Date"] >= "2025-04-01") & \
           (df["Published Date"] <= "2026-03-31 23:59:59")
    fy_df = df[mask].copy()
    fy_df["_value"] = (
        fy_df["Tender Value in ₹"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .pipe(pd.to_numeric, errors="coerce")
    )
    return fy_df["_value"].sum(), int(mask.sum())

total, count = annual_tender_value_fy2025_26("data/assam_all_tenders.csv")
print(f"FY 2025-26 — {count} tenders, Total Value: ₹{total:,.0f}")